# Generated by Django 3.0.6 on 2020-06-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name_plural': 'Register'},
        ),
    ]
