# Generated by Django 3.0.6 on 2020-06-03 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_auto_20200603_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
